from django.views import View
from django.http import JsonResponse
from django.core.mail import send_mail
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from .models import ContactMessage
import json
import os


@method_decorator(csrf_exempt, name='dispatch')
class ContactFormView(View):
    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)

            first_name = data.get('firstName')
            last_name = data.get('lastName')
            email = data.get('email')
            phone = data.get('phone')
            message = data.get('message')
            location = data.get('location')

            # Save to DB
            ContactMessage.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone=phone,
                message=message,
                location=location
            )

            # Site owner emails and sender from .env
            site_owner_emails = os.getenv('SITE_OWNER_EMAILS', '').split(',')
            sender_email = os.getenv('EMAIL_HOST_USER')

            # --- 1️⃣ Email to Site Owners ---
            owner_subject = f"New Enquiry Received – {first_name} {last_name}"
            owner_message = f"""
Dear Team,

A new enquiry has been submitted through the website contact form. Please find the details below:

Name: {first_name} {last_name}
Email: {email}
Phone: {phone}

Location:
{location or 'N/A'}

Message:
{message}

---
This is an automated email generated by the system. Please do not reply directly to this message.
If a response is required, kindly reach out to the sender using the contact details provided above.

Best regards,
System Notification
VR Property Solutions
"""

            send_mail(
                subject=owner_subject,
                message=owner_message.strip(),
                from_email=sender_email,
                recipient_list=site_owner_emails,
                fail_silently=False,
            )

            # --- 2️⃣ Acknowledgment Email to User ---
            user_subject = "Thank you for contacting VR Property Solutions"
            user_message = f"""
Hi {first_name},

Thank you for reaching out to us. We’ve received your message and our team will get back to you shortly.

If your enquiry is urgent, please contact us directly through the details mentioned on our website.
https://vrpropertysol.com/

Best regards,
VR Property Solutions Team
"""

            send_mail(
                subject=user_subject,
                message=user_message.strip(),
                from_email=sender_email,
                recipient_list=[email],
                fail_silently=False,
            )

            return JsonResponse({'success': True, 'message': 'Message sent successfully!'})

        except Exception as e:
            print("Error:", e)
            return JsonResponse({'success': False, 'error': str(e)}, status=400)

    def get(self, request, *args, **kwargs):
        return JsonResponse({'message': 'Use POST to send data'}, status=405)
